project:
  name: DK-01

tree:

  - type: folder
    name: docs

    children:

      - type: folder
        name: 00_Project

      - type: folder
        name: 01_Requirements

      - type: folder
        name: 02_System

      - type: folder
        name: 03_Electronics

  - type: folder
    name: hardware

  - type: folder
    name: firmware

  - type: folder
    name: mechanical

  - type: folder
    name: production

  - type: folder
    name: resources