project:

  name: DK-01

tree:

  - type: file
    name: README.md

  - type: file
    name: CHANGELOG.md

  - type: file
    name: LICENSE.md

  - type: folder
    name: docs

    children:

      - type: folder
        name: 00_Project

      - type: file
        name: README.md

  - type: folder
    name: hardware

  - type: folder
    name: firmware

  - type: folder
    name: production

  - type: folder
    name: tests